### ISSUE TITLE
Couldn't find Upload ActiveGate Plugin option from UI

### ISSUE THREAD

**Issue by tedteng** [dynatrace-innovationlab/activegateplugin-k8s#1]
Hi in Dynatrace SaaS(opd84192.live.dynatrace.com),I couldn't find Upload ActiveGate Plugin from the Dynatrace UI, was ok use "Upload OneAgent Plugin" to upload it ?

**Comment by dirkwall** [comment]
Hi, ActiveGate plugins will be GA in the near future. Until then, you would need to get in touch with your Dynatrace contact to enable ActiveGate plugins in your environment. Then you will be able to upload ActiveGate plugins as well.
Cheers!
